output_dir: /work/hdd/bdxf/nstjohn/LVSM/inference

model:
  class_name: model.LVSM_scene_encoder_decoder.Images2LatentScene

  image_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 9

  target_pose_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 6

  transformer:
    d: 768
    d_head: 64
    encoder_n_layer: 12
    decoder_n_layer: 12
    special_init: true
    depth_init: true
    use_qk_norm: true
    n_latent_vectors: 3072

  first_stage_config:
    target: model.autoencoder_vae.AutoencoderKL
    params:
      ckpt_path: /work/hdd/bdxf/nstjohn/LVSM/autoencoder/checkpoints/latest.pt
      monitor: val/rec_loss
    embed_dim: 16
    ddconfig:
      double_z: true
      z_channels: 16
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 2, 4]
      num_res_blocks: 2
      attn_resolutions: []
      attn_type: vanilla
      dropout: 0.0
    lossconfig:
      disc_start: 50001
      kl_weight: 0.000001
      disc_weight: 0.5
      perceptual_weight: 1.0
      disc_num_layers: 3
      disc_in_channels: 3
      disc_ndf: 64
      disc_loss: hinge

training:
  amp_dtype: bf16
  batch_size_per_gpu: 8
  checkpoint_dir: /work/hdd/bdxf/nstjohn/LVSM/experiments/smoke_test/checkpoints
  dataset_name: data.dataset_scene.Dataset
  dataset_path: /work/hdd/bdxf/nstjohn/dl3dv_processed/test/full_list.txt
  num_input_views: 2
  num_target_views: 6
  num_threads: 8
  num_views: 8
  num_workers: 4
  prefetch_factor: 4
  scene_scale_factor: 1.35
  square_crop: true
  target_has_input: true
  use_amp: true
  use_rel_pose: false
  use_tf32: true
  lpips_loss_weight: 0.0
  l2_loss_weight: 1.0
  perceptual_loss_weight: 0.5
  view_selector:
    max_frame_dist: 192
    min_frame_dist: 25

inference_out_dir: /work/hdd/bdxf/nstjohn/LVSM/inference

inference:
  if_inference: true
  compute_metrics: false
  render_video: false
  render_video_config:
    traj_type: interpolate
    num_frames: 60
    loop_video: true
    order_poses: false